// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtseapilmrfcylvgqikk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0c2VhcGlsbXJmY3lsdmdxaWtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNTUzNTEsImV4cCI6MjA3OTYzMTM1MX0.LXq4vKg6R_0mSGhXnON_bx1SCG1pHsomuzzDx4_DkAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});